import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:pizzaapp/injection_pizza.dart' as packageDI;
import 'package:pizzaapp/injection_pizza.dart';
import 'package:url_strategy/url_strategy.dart';

void main() async {
  //will wait tilkl the below file has initialized all the required dependencies.
  await packageDI.init();

  setPathUrlStrategy();// to remove the # from route generated by gorouter.
  runApp(MaterialApp.router(
    debugShowCheckedModeBanner: false,
    routeInformationProvider: serviceLocator.get<
        GoRouteInformationProvider>(), // will provide all the info related to routes.
    routeInformationParser: serviceLocator.get<
        GoRouteInformationParser>(), //converts route information in terms the router lib can understand
    routerDelegate: serviceLocator.get<
        GoRouterDelegate>(), //will implement and map the information obtained from info. parser.
  ));
}
